[package]
name = "wii-disc-info"
version = "0.9.2"
edition = "2024"
rust-version = "1.87"
authors = ["Manuel Quarneti <mq1@ik.me>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mq1/wii-disc-info-rs"
homepage = "https://github.com/mq1/wii-disc-info-rs"
description = "Query info about wii disc files (without requiring Seek)"

[features]
default = ["deflate"]
deflate = ["miniz_oxide"]

[dependencies]
thiserror = "2"
strum = "0.28"
strum_macros = "0.28"
smol_str = "0.3"
miniz_oxide = { version = "0.9", optional = true, default-features = false }
futures-lite = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
